-- upgrade --
CREATE TABLE IF NOT EXISTS `aerich` (
    `id` INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `version` VARCHAR(255) NOT NULL,
    `app` VARCHAR(20) NOT NULL,
    `content` JSON NOT NULL
) CHARACTER SET utf8mb4;
CREATE TABLE IF NOT EXISTS `github_users` (
    `id` INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `gid` INT NOT NULL UNIQUE,
    `email` VARCHAR(100) NOT NULL UNIQUE DEFAULT '',
    `username` VARCHAR(100) NOT NULL UNIQUE,
    `picture` VARCHAR(100) NOT NULL  DEFAULT '',
    `link` VARCHAR(100) NOT NULL  DEFAULT ''
) CHARACTER SET utf8mb4;
CREATE TABLE IF NOT EXISTS `users` (
    `id` INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `email` VARCHAR(100) NOT NULL,
    `name` VARCHAR(100) NOT NULL UNIQUE,
    `password` LONGTEXT NOT NULL,
    `active` BOOL NOT NULL  DEFAULT 1
) CHARACTER SET utf8mb4;
